AWSTemplateFormatVersion: 2010-09-09
Description: >-
  CustomerAccessRole- Cross account role.
Outputs:
  RoleARN:
    Description: The ARN of the role that can be assumed by the other account.
    Value: !GetAtt 
      - CustomerAccessRole
      - Arn
Parameters:
  OtherAccountNumber:
    AllowedPattern: '[0-9]+'
    Description: The 12 digit AWS account number to grant access to.
    MaxLength: '12'
    MinLength: '12'
    Type: String
Resources:
  CustomerAccessRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: 'sts:AssumeRole'
            Effect: Allow
            Principal:
              AWS: !Join 
                - ''
                - - 'arn:aws:iam::'
                  - !Ref OtherAccountNumber
                  - ':root'
            Sid: ''
        Version: 2012-10-17
      Path: /
      RoleName: 'CustomerAccessRole'
      Policies:
        - PolicyName: 'CustAdministratorAccess'
          PolicyDocument: 
            Version: "2012-10-17"
            Statement: 
              - 
                Effect: "Allow"
                Action: "*"
                Resource: "*"
    Type: 'AWS::IAM::Role'